#!/usr/bin/env bash

set -ex

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

if [ -z "$1" ]; then
  echo "Usage: $0 <version>"
  exit 1
fi

$SCRIPT_DIR/npm install "@editframe/api@${1}" "@editframe/assets@${1}" "@editframe/elements@${1}" "@editframe/react@${1}" --legacy-peer-deps

git add package.json package-lock.json