/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string>;

export type Timestamp = ColumnType<Date, Date | string>;

export interface ApiWebhookEventDeliveries {
  attempt_number: number;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  request_headers: string;
  response_headers: string;
  response_status: number;
  response_text: string;
  status: string;
  webhook_event_id: string;
}

export interface ApiWebhookEvents {
  api_key_id: string;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  failed_at: Timestamp | null;
  id: Generated<string>;
  json_payload: string;
  org_id: string;
  qualified_table: string;
  record_id: string;
  topic: string;
  updated_at: Generated<Timestamp | null>;
  url: string;
}

export interface ApiWebhooksRequests {
  api_key_id: string;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  last_attempted_at: Timestamp | null;
  org_id: string;
  retry_count: Generated<number | null>;
  status_code: number;
  topic: string | null;
  webhook_url: string | null;
}

export interface ApiWebhookTopics {
  comment: string;
  name: string;
}

export interface HdbCatalogEventInvocationLogs {
  created_at: Generated<Timestamp | null>;
  event_id: string | null;
  id: Generated<string>;
  request: Json | null;
  response: Json | null;
  status: number | null;
  trigger_name: string | null;
}

export interface HdbCatalogEventLog {
  archived: Generated<boolean>;
  created_at: Generated<Timestamp | null>;
  delivered: Generated<boolean>;
  error: Generated<boolean>;
  id: Generated<string>;
  locked: Timestamp | null;
  next_retry_at: Timestamp | null;
  payload: Json;
  schema_name: string;
  table_name: string;
  tries: Generated<number>;
  trigger_name: string;
}

export interface HdbCatalogHdbActionLog {
  action_name: string | null;
  created_at: Generated<Timestamp>;
  errors: Json | null;
  id: Generated<string>;
  input_payload: Json;
  request_headers: Json;
  response_payload: Json | null;
  response_received_at: Timestamp | null;
  session_variables: Json;
  status: string;
}

export interface HdbCatalogHdbCronEventInvocationLogs {
  created_at: Generated<Timestamp | null>;
  event_id: string | null;
  id: Generated<string>;
  request: Json | null;
  response: Json | null;
  status: number | null;
}

export interface HdbCatalogHdbCronEvents {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  next_retry_at: Timestamp | null;
  scheduled_time: Timestamp;
  status: Generated<string>;
  tries: Generated<number>;
  trigger_name: string;
}

export interface HdbCatalogHdbEventLogCleanups {
  deleted_event_invocation_logs: number | null;
  deleted_event_logs: number | null;
  id: Generated<string>;
  scheduled_at: Timestamp;
  status: string;
  trigger_name: string;
}

export interface HdbCatalogHdbMetadata {
  id: number;
  metadata: Json;
  resource_version: Generated<number>;
}

export interface HdbCatalogHdbScheduledEventInvocationLogs {
  created_at: Generated<Timestamp | null>;
  event_id: string | null;
  id: Generated<string>;
  request: Json | null;
  response: Json | null;
  status: number | null;
}

export interface HdbCatalogHdbScheduledEvents {
  comment: string | null;
  created_at: Generated<Timestamp | null>;
  header_conf: Json | null;
  id: Generated<string>;
  next_retry_at: Timestamp | null;
  payload: Json | null;
  retry_conf: Json | null;
  scheduled_time: Timestamp;
  status: Generated<string>;
  tries: Generated<number>;
  webhook_conf: Json;
}

export interface HdbCatalogHdbSchemaNotifications {
  id: number;
  instance_id: string;
  notification: Json;
  resource_version: Generated<number>;
  updated_at: Generated<Timestamp | null>;
}

export interface HdbCatalogHdbSourceCatalogVersion {
  upgraded_on: Timestamp;
  version: string;
}

export interface HdbCatalogHdbVersion {
  cli_state: Generated<Json>;
  console_state: Generated<Json>;
  ee_client_id: string | null;
  ee_client_secret: string | null;
  hasura_uuid: Generated<string>;
  upgraded_on: Timestamp;
  version: string;
}

export interface IdentityApiKeys {
  created_at: Generated<Timestamp>;
  expiration_reminder_sent_at: Timestamp | null;
  expired_at: Timestamp | null;
  hash: Buffer;
  id: Generated<string>;
  name: string;
  org_id: string;
  salt: Buffer;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
  webhook_events: Generated<string[]>;
  webhook_secret: Generated<string>;
  webhook_url: string | null;
}

export interface IdentityEmailConfirmations {
  confirmation_token: Generated<string>;
  confirmed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  email_password_id: string;
  id: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface IdentityEmailPasswords {
  created_at: Generated<Timestamp>;
  email_address: string;
  hash: Buffer;
  id: Generated<string>;
  salt: Buffer;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface IdentityInviteForDisplay {
  accepted_at: Timestamp | null;
  created_at: Timestamp | null;
  creator_id: string | null;
  denied_at: Timestamp | null;
  email_address: string | null;
  id: string | null;
  invite_token: string | null;
  invited_by: string | null;
  org_display_name: string | null;
  org_id: string | null;
  role: string | null;
  updated_at: Timestamp | null;
}

export interface IdentityInvites {
  accepted_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  creator_id: string;
  denied_at: Timestamp | null;
  email_address: string;
  id: Generated<string>;
  invite_token: Generated<string>;
  org_id: string;
  role: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface IdentityMagicLinkTokens {
  claimed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  email_address: string;
  token: Generated<string>;
  updated_at: Generated<Timestamp | null>;
  user_id: string;
}

export interface IdentityMemberships {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  org_id: string;
  role: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface IdentityOrgs {
  created_at: Generated<Timestamp>;
  display_name: string;
  id: Generated<string>;
  is_paid: Generated<boolean | null>;
  primary_user_id: string;
  updated_at: Generated<Timestamp>;
  website: string | null;
}

export interface IdentityPasswordResets {
  claimed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  reset_token: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface IdentityRoles {
  comment: string;
  id: Generated<string>;
}

export interface IdentityUsers {
  created_at: Generated<Timestamp>;
  first_name: string | null;
  id: Generated<string>;
  last_name: string | null;
  metadata: Json | null;
  referral: string | null;
  updated_at: Generated<Timestamp>;
}

export interface IdentityValidEmailConfirmations {
  confirmation_token: string | null;
  confirmed_at: Timestamp | null;
  created_at: Timestamp | null;
  id: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface IdentityValidMagicLinksTokens {
  claimed_at: Timestamp | null;
  created_at: Timestamp | null;
  email_address: string | null;
  token: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface IdentityValidPasswordResets {
  claimed_at: Timestamp | null;
  created_at: Timestamp | null;
  id: string | null;
  reset_token: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface Video2CaptionFiles {
  api_key_id: string | null;
  byte_size: Generated<number>;
  complete: Generated<boolean | null>;
  created_at: Generated<Timestamp>;
  creator_id: string;
  filename: string;
  id: Generated<string>;
  md5: string;
  org_id: string;
}

export interface Video2FileProcessors {
  comment: string;
  value: string;
}

export interface Video2FileStatuses {
  comment: string;
  value: string;
}

export interface Video2FileTypes {
  comment: string;
  value: string;
}

export interface Video2Files {
  api_key_id: string | null;
  byte_size: number | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  creator_id: string;
  expires_at: Timestamp | null;
  filename: string;
  height: number | null;
  id: string;
  md5: string | null;
  mime_type: string | null;
  next_byte: Generated<number>;
  org_id: string;
  remote_uri: string | null;
  status: Generated<"created" | "uploading" | "processing" | "ready" | "failed">;
  type: "video" | "image" | "caption";
  width: number | null;
}

export interface Video2ImageFiles {
  api_key_id: string | null;
  byte_size: number;
  complete: Generated<boolean | null>;
  created_at: Generated<Timestamp>;
  creator_id: string;
  expires_at: Timestamp | null;
  filename: string;
  height: number | null;
  id: string;
  md5: string | null;
  mime_type: string;
  next_byte: Generated<number>;
  org_id: string;
  remote_uri: string | null;
  width: number | null;
}

export interface Video2IsobmffFiles {
  api_key_id: string | null;
  created_at: Generated<Timestamp>;
  creator_id: string;
  expires_at: Timestamp | null;
  filename: string;
  fragment_index_complete: Generated<boolean>;
  id: Generated<string>;
  md5: string;
  org_id: string;
}

export interface Video2IsobmffSourceTypes {
  value: string;
}

export interface Video2IsobmffTrackFragments {
  bytesize: number;
  duration_ms: number;
  file_id: string;
  offset: number;
  sequence_number: number;
  start_ms: number;
  track_id: number;
}

export interface Video2IsobmffTracks {
  api_key_id: string | null;
  byte_size: number;
  codec_name: string;
  complete: Generated<boolean>;
  creator_id: string;
  duration_ms: number;
  file_id: Generated<string>;
  last_received_byte: Generated<number>;
  next_byte: Generated<number>;
  org_id: string;
  probe_info: Json;
  remote_uri: string | null;
  track_id: number;
  type: string;
}

export interface Video2IsobmffTrackTypes {
  comment: string;
  value: string;
}

export interface Video2ProcessHtml {
  api_key_id: string | null;
  attempt_count: Generated<number>;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  creator_id: string;
  failed_at: Timestamp | null;
  html: string;
  id: Generated<string>;
  org_id: string;
  render_id: string;
  started_at: Timestamp;
}

export interface Video2ProcessHtmlAttempts {
  attempt_number: number;
  completed_at: Timestamp | null;
  failed_at: Timestamp | null;
  id: Generated<string>;
  process_html_id: string;
  started_at: Timestamp;
}

export interface Video2ProcessIsobmff {
  api_key_id: string | null;
  attempt_count: Generated<number>;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  creator_id: string;
  failed_at: Timestamp | null;
  id: Generated<string>;
  isobmff_expires_at: Timestamp | null;
  isobmff_file_id: string | null;
  org_id: string;
  source_type: "url" | "unprocessed_file" | "file";
  started_at: Timestamp | null;
  unprocessed_file_id: string | null;
  url: string | null;
}

export interface Video2ProcessIsobmffAttempts {
  attempt_number: number;
  completed_at: Timestamp | null;
  failed_at: Timestamp | null;
  id: Generated<string>;
  log_info: string | null;
  process_isobmff_id: string;
  public_error: string | null;
  started_at: Generated<Timestamp>;
}

export interface Video2RenderFragments {
  attempt_number: Generated<number>;
  completed_at: Timestamp | null;
  failed_at: Timestamp | null;
  last_error: string | null;
  render_id: string;
  segment_id: string;
  started_at: Timestamp;
}

export interface Video2Renders {
  api_key_id: string | null;
  attempt_count: Generated<number>;
  byte_size: number | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  creator_id: string;
  duration_ms: number | null;
  failed_at: Timestamp | null;
  failure_detail: Json | null;
  fps: Numeric;
  height: number | null;
  html: string | null;
  id: Generated<string>;
  initializer_complete: Generated<boolean>;
  md5: string | null;
  metadata: Record<string, string>;
  org_id: string;
  output_config: Json | null;
  restricted: Generated<boolean>;
  started_at: Timestamp | null;
  status: "created" | "queued" | "rendering" | "complete" | "failed";
  strategy: string;
  width: number | null;
  work_slice_ms: Generated<number>;
}

export interface Video2RenderStatuses {
  comment: string;
  value: string;
}

export interface Video2RenderStrategies {
  comment: string;
  value: string;
}

export interface Video2TranscriptionFragments {
  attempt_number: Generated<number>;
  completed_at: Timestamp | null;
  failed_at: Timestamp | null;
  last_error: string | null;
  sequence_number: number;
  started_at: Timestamp;
  transcription_id: string;
}

export interface Video2Transcriptions {
  api_key_id: string | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  creator_id: string;
  failed_at: Timestamp | null;
  file_id: string;
  id: Generated<string>;
  org_id: string;
  status: Generated<string>;
  track_id: number;
  updated_at: Generated<Timestamp>;
  work_slice_ms: number;
}

export interface Video2TranscriptionStatuses {
  comment: string;
  value: string;
}

export interface Video2UnprocessedFiles {
  api_key_id: string | null;
  byte_size: Generated<number>;
  complete: Generated<boolean>;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  creator_id: string;
  filename: string;
  id: Generated<string>;
  last_received_byte: number | null;
  md5: string;
  next_byte: Generated<number>;
  org_id: string;
  remote_uri: string | null;
}

export interface VideoAudioTracks {
  bytesize: number;
  channel_count: number;
  codec: string;
  complete: Generated<boolean>;
  creator_id: string;
  duration_ms: number;
  format: string;
  id: Generated<string>;
  next_byte: Generated<number>;
  /**
   * A loose reference that will be shared between audio/video tracks that came from the same original container. Will be used if we ever need to re-combine tracks.
   */
  original_container_id: string;
  project_id: string;
  remote_uri: string | null;
  samplerate: number;
}

export interface VideoImages {
  bytesize: number;
  complete: Generated<boolean>;
  created_at: Generated<Timestamp>;
  creator_id: string;
  format: string;
  height: number;
  id: Generated<string>;
  next_byte: Generated<number>;
  project_id: string;
  remote_uri: string | null;
  width: number;
}

export interface VideoProjects {
  created_at: Generated<Timestamp>;
  creator_id: string;
  id: Generated<string>;
  org_id: string;
  title: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface VideoProjectUpdates {
  id: Generated<Int8>;
  project_id: string;
  update: Buffer;
}

export interface VideoRenders {
  created_at: Generated<Timestamp>;
  creator_id: string;
  id: Generated<string>;
  snapshot: Json;
  updated_at: Generated<Timestamp>;
}

export interface VideoVideoTrackFragments {
  duration_ms: number;
  offset: number;
  sequence_number: number;
  size: number;
  start_ms: number;
  video_track_id: string;
}

export interface VideoVideoTracks {
  bytesize: number;
  codec: string;
  complete: Generated<boolean>;
  creator_id: string;
  duration_ms: number;
  format: string;
  height: number;
  id: Generated<string>;
  next_byte: Generated<number>;
  /**
   * A loose reference that will be shared between audio/video tracks that came from the same original container. Will be used if we ever need to re-combine tracks.
   */
  original_container_id: string;
  project_id: string;
  remote_uri: string | null;
  width: number;
}

export interface DB {
  "api.webhook_event_deliveries": ApiWebhookEventDeliveries;
  "api.webhook_events": ApiWebhookEvents;
  "api.webhook_topics": ApiWebhookTopics;
  "api.webhooks_requests": ApiWebhooksRequests;
  "hdb_catalog.event_invocation_logs": HdbCatalogEventInvocationLogs;
  "hdb_catalog.event_log": HdbCatalogEventLog;
  "hdb_catalog.hdb_action_log": HdbCatalogHdbActionLog;
  "hdb_catalog.hdb_cron_event_invocation_logs": HdbCatalogHdbCronEventInvocationLogs;
  "hdb_catalog.hdb_cron_events": HdbCatalogHdbCronEvents;
  "hdb_catalog.hdb_event_log_cleanups": HdbCatalogHdbEventLogCleanups;
  "hdb_catalog.hdb_metadata": HdbCatalogHdbMetadata;
  "hdb_catalog.hdb_scheduled_event_invocation_logs": HdbCatalogHdbScheduledEventInvocationLogs;
  "hdb_catalog.hdb_scheduled_events": HdbCatalogHdbScheduledEvents;
  "hdb_catalog.hdb_schema_notifications": HdbCatalogHdbSchemaNotifications;
  "hdb_catalog.hdb_source_catalog_version": HdbCatalogHdbSourceCatalogVersion;
  "hdb_catalog.hdb_version": HdbCatalogHdbVersion;
  "identity.api_keys": IdentityApiKeys;
  "identity.email_confirmations": IdentityEmailConfirmations;
  "identity.email_passwords": IdentityEmailPasswords;
  "identity.invite_for_display": IdentityInviteForDisplay;
  "identity.invites": IdentityInvites;
  "identity.magic_link_tokens": IdentityMagicLinkTokens;
  "identity.memberships": IdentityMemberships;
  "identity.orgs": IdentityOrgs;
  "identity.password_resets": IdentityPasswordResets;
  "identity.roles": IdentityRoles;
  "identity.users": IdentityUsers;
  "identity.valid_email_confirmations": IdentityValidEmailConfirmations;
  "identity.valid_magic_links_tokens": IdentityValidMagicLinksTokens;
  "identity.valid_password_resets": IdentityValidPasswordResets;
  "video.audio_tracks": VideoAudioTracks;
  "video.images": VideoImages;
  "video.project_updates": VideoProjectUpdates;
  "video.projects": VideoProjects;
  "video.renders": VideoRenders;
  "video.video_track_fragments": VideoVideoTrackFragments;
  "video.video_tracks": VideoVideoTracks;
  "video2.caption_files": Video2CaptionFiles;
  "video2.file_processors": Video2FileProcessors;
  "video2.file_statuses": Video2FileStatuses;
  "video2.file_types": Video2FileTypes;
  "video2.files": Video2Files;
  "video2.image_files": Video2ImageFiles;
  "video2.isobmff_files": Video2IsobmffFiles;
  "video2.isobmff_source_types": Video2IsobmffSourceTypes;
  "video2.isobmff_track_fragments": Video2IsobmffTrackFragments;
  "video2.isobmff_track_types": Video2IsobmffTrackTypes;
  "video2.isobmff_tracks": Video2IsobmffTracks;
  "video2.process_html": Video2ProcessHtml;
  "video2.process_html_attempts": Video2ProcessHtmlAttempts;
  "video2.process_isobmff": Video2ProcessIsobmff;
  "video2.process_isobmff_attempts": Video2ProcessIsobmffAttempts;
  "video2.render_fragments": Video2RenderFragments;
  "video2.render_statuses": Video2RenderStatuses;
  "video2.render_strategies": Video2RenderStrategies;
  "video2.renders": Video2Renders;
  "video2.transcription_fragments": Video2TranscriptionFragments;
  "video2.transcription_statuses": Video2TranscriptionStatuses;
  "video2.transcriptions": Video2Transcriptions;
  "video2.unprocessed_files": Video2UnprocessedFiles;
}
