services:
  jit-transcoding:
    image: telecine-runner
    pull_policy: never
    env_file:
      - ${PWD}/.env
    depends_on:
      - runner
    working_dir: /app
    environment:
      - SHELL=/bin/sh
      - OTEL_SERVICE_NAME=jit-transcoding
      - PORT=3001
    volumes_from:
      - runner
    stop_grace_period: 1s
    init: true
    networks:
      - default
      - traefik-shared
    command: ["npx", "tsx", "--watch", "/app/services/jit-transcoding/server.ts" ]
    labels:
      traefik.enable: true
      traefik.http.routers.jit-transcoding.rule: "Host(`${WORKTREE_DOMAIN:-localhost}`) && PathPrefix(`/api/v1/transcode`)"
      traefik.http.routers.jit-transcoding.entrypoints: web
      traefik.http.routers.jit-transcoding.priority: 1000
      traefik.http.routers.jit-transcoding.service: jit-transcoding
      traefik.http.services.jit-transcoding.loadbalancer.server.port: 3001

networks:
  traefik-shared:
    name: telecine-traefik
    external: true