FROM node:22 AS installer

# xvfb is used to run electron as "headless"
# ffmpeg is used to encode/mux video
# libc6-amd64-cross is required for running odiff-bin on M1 in docker
# libasound2 through libnss3 are required for running electron
RUN apt-get -y update && \
  apt-get install -y --fix-missing \
  xvfb \
  ffmpeg \
  libc6-amd64-cross \
  libatk-bridge2.0-0 \
  libatk1.0-0 \
  libcups2 \
  libdrm2 \
  libgbm1 \
  libgtk-3-0 \
  libnss3 \
  libxss1 \
  libasound2 \
  libgconf-2-4 \
  libnss3 \
  && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*

RUN npm install -g hasura-cli@2.36.1
RUN npm install -g tsx

WORKDIR /app

COPY .editframe-downloads/editframe-v32.1.2.zip /tmp/editframe-electron.zip
RUN mkdir -p /electron-build && \
  unzip /tmp/editframe-electron.zip -d /electron-build && \
  rm /tmp/editframe-electron.zip


