ARG HASURA_VERSION=v2.36.0

FROM hasura/graphql-engine:${HASURA_VERSION}
RUN curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | VERSION=${HASURA_VERSION} bash

COPY ./services/graphql-engine/metadata /metadata
COPY ./services/graphql-engine/migrations /migrations
COPY ./services/graphql-engine/config.prod.yaml /config.yaml
COPY ./services/graphql-engine/migration-job.sh /migration-job.sh

CMD ["/bin/sh", "/migration-job.sh"]
