CREATE TABLE "video2"."files" (
  "id" uuid NOT NULL,
  "org_id" uuid NOT NULL,
  "creator_id" uuid NOT NULL,
  "api_key_id" uuid,
  "filename" text NOT NULL,
  "byte_size" integer,
  "md5" text,
  "type" text NOT NULL,
  "status" text NOT NULL DEFAULT 'created',
  "mime_type" text,
  "width" integer,
  "height" integer,
  "remote_uri" text,
  "next_byte" integer NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL DEFAULT now(),
  "completed_at" timestamptz,
  "expires_at" timestamptz,
  PRIMARY KEY ("id"),
  FOREIGN KEY ("org_id") REFERENCES "identity"."orgs"("id") ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY ("creator_id") REFERENCES "identity"."users"("id") ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY ("api_key_id") REFERENCES "identity"."api_keys"("id") ON UPDATE SET NULL ON DELETE SET NULL,
  FOREIGN KEY ("type") REFERENCES "video2"."file_types"("value") ON UPDATE RESTRICT ON DELETE RESTRICT,
  FOREIGN KEY ("status") REFERENCES "video2"."file_statuses"("value") ON UPDATE RESTRICT ON DELETE RESTRICT
);
