export const BASE_QUEUE_CONFIGS = {
  PROCESS_HTML_FINALIZER_WEBSOCKET_HOST: "http://localhost:80",
  PROCESS_HTML_FINALIZER_MAX_WORKER_COUNT: "1",
  PROCESS_HTML_FINALIZER_WORKER_CONCURRENCY: "5",

  PROCESS_HTML_INITIALIZER_WEBSOCKET_HOST: "http://localhost:80",
  PROCESS_HTML_INITIALIZER_MAX_WORKER_COUNT: "1",
  PROCESS_HTML_INITIALIZER_WORKER_CONCURRENCY: "5",

  PROCESS_ISOBMFF_WEBSOCKET_HOST: "http://localhost:80",
  PROCESS_ISOBMFF_MAX_WORKER_COUNT: "1",
  PROCESS_ISOBMFF_WORKER_CONCURRENCY: "10",

  RENDER_INITIALIZER_WEBSOCKET_HOST: "http://localhost:80",
  RENDER_INITIALIZER_MAX_WORKER_COUNT: "1",
  RENDER_INITIALIZER_WORKER_CONCURRENCY: "2",

  RENDER_FRAGMENT_WEBSOCKET_HOST: "http://localhost:80",
  RENDER_FRAGMENT_MAX_WORKER_COUNT: "1",
  RENDER_FRAGMENT_WORKER_CONCURRENCY: "2",

  RENDER_FINALIZER_WEBSOCKET_HOST: "http://localhost:80",
  RENDER_FINALIZER_MAX_WORKER_COUNT: "1",
  RENDER_FINALIZER_WORKER_CONCURRENCY: "5",

  INGEST_IMAGE_WEBSOCKET_HOST: "http://localhost:80",
  INGEST_IMAGE_MAX_WORKER_COUNT: "1",
  INGEST_IMAGE_WORKER_CONCURRENCY: "5",
};
