-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE INDEX renders_org_id_created_at_idx
-- ON video2.renders (org_id, created_at DESC);
