export interface PropertyDefinition {
  name: string;
  type: string;
  access: "R" | "W" | "R/W";
  useCase: string;
  category?: string;
  domReadable?: boolean | string;
  domWritable?: boolean | string;
  htmlAttribute?: boolean | string;
  defaultValue?: string;
}

export const audioElementProperties: PropertyDefinition[] = [
  // Media Source
  {
    name: "assetId",
    type: "string",
    access: "R/W",
    useCase: "Production rendering with uploaded assets",
    category: "Media Source",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "asset-id",
  },
  {
    name: "src",
    type: "string",
    access: "R/W",
    useCase: "Development/preview with JIT transcoding",
    category: "Media Source",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "src",
    defaultValue: '""',
  },
  // Audio Control
  {
    name: "volume",
    type: "number",
    access: "R/W",
    useCase: "Audio volume level (0.0 to 1.0)",
    category: "Audio Control",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "volume",
    defaultValue: "1.0",
  },
  {
    name: "mute",
    type: "boolean",
    access: "R/W",
    useCase: "Mute audio output",
    category: "Audio Control",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "mute",
    defaultValue: "false",
  },
  // Trimming & Editing
  {
    name: "trimStartMs",
    type: "timestring",
    access: "R/W",
    useCase: "Relative trimming from start",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "trimstart",
  },
  {
    name: "trimEndMs",
    type: "timestring",
    access: "R/W",
    useCase: "Relative trimming from end",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "trimend",
  },
  {
    name: "sourceInMs",
    type: "timestring",
    access: "R/W",
    useCase: "Absolute source start time",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "sourcein",
  },
  {
    name: "sourceOutMs",
    type: "timestring",
    access: "R/W",
    useCase: "Absolute source end time",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "sourceout",
  },
  // Time Coordinates
  {
    name: "startTimeMs",
    type: "number",
    access: "R",
    useCase: "Element start in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "endTimeMs",
    type: "number",
    access: "R",
    useCase: "Element end in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "durationMs",
    type: "number",
    access: "R",
    useCase: "Computed element duration",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "duration",
    type: "timestring",
    access: "R/W",
    useCase: "Explicit duration override",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "duration",
  },
  {
    name: "offset",
    type: "timestring",
    access: "R/W",
    useCase: "Offset from parent start time",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "offset",
    defaultValue: "0",
  },
  {
    name: "startOffsetMs",
    type: "number",
    access: "R/W",
    useCase: "Start offset in milliseconds",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "startoffset",
    defaultValue: "0",
  },
  {
    name: "currentTimeMs",
    type: "number",
    access: "R/W",
    useCase: "Current time in root timeline",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
  },
  {
    name: "ownCurrentTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time in element scope",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "currentSourceTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time in source audio",
    category: "Time Coordinates",
    domReadable: true,
  },
  // Playback
  {
    name: "loop",
    type: "boolean",
    access: "R/W",
    useCase: "Loop playback when reaching end",
    category: "Playback",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "loop",
    defaultValue: "false",
  },
  // Hierarchy
  {
    name: "parentTimegroup",
    type: "<ef-timegroup> | null",
    access: "R",
    useCase: "Immediate containing timegroup",
    category: "Hierarchy",
    domReadable: true,
  },
  {
    name: "rootTimegroup",
    type: "<ef-timegroup> | null",
    access: "R",
    useCase: "Root timeline timegroup",
    category: "Hierarchy",
    domReadable: true,
  },
  // Performance & Buffering
  {
    name: "audioBufferDurationMs",
    type: "number",
    access: "R/W",
    useCase: "Audio buffer duration (ms)",
    category: "Performance & Buffering",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "audio-buffer-duration",
    defaultValue: "10000",
  },
  {
    name: "maxAudioBufferFetches",
    type: "number",
    access: "R/W",
    useCase: "Parallel audio segment fetch limit",
    category: "Performance & Buffering",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "max-audio-buffer-fetches",
    defaultValue: "2",
  },
  {
    name: "enableAudioBuffering",
    type: "boolean",
    access: "R/W",
    useCase: "Enable/disable audio buffering",
    category: "Performance & Buffering",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "enable-audio-buffering",
    defaultValue: "true",
  },
  // Audio Analysis
  {
    name: "fftSize",
    type: "number",
    access: "R/W",
    useCase: "FFT frequency bins (power of 2)",
    category: "Audio Analysis",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "fft-size",
    defaultValue: "128",
  },
  {
    name: "fftDecay",
    type: "number",
    access: "R/W",
    useCase: "FFT smoothing frame count",
    category: "Audio Analysis",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "fft-decay",
    defaultValue: "8",
  },
  {
    name: "fftGain",
    type: "number",
    access: "R/W",
    useCase: "FFT amplitude multiplier",
    category: "Audio Analysis",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "fft-gain",
    defaultValue: "3.0",
  },
  {
    name: "interpolateFrequencies",
    type: "boolean",
    access: "R/W",
    useCase: "Interpolate missing frequencies",
    category: "Audio Analysis",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "interpolate-frequencies",
    defaultValue: "false",
  },
];

