export interface PropertyDefinition {
  name: string;
  type: string;
  access: "R" | "W" | "R/W";
  useCase: string;
  category?: string;
  domReadable?: boolean | string;
  domWritable?: boolean | string;
  htmlAttribute?: boolean | string;
  defaultValue?: string;
}

export const audioElementProperties: PropertyDefinition[] = [
  {
    name: "assetId",
    type: "string",
    access: "R/W",
    useCase: "Production rendering with uploaded assets",
    category: "Media Source",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "asset-id",
  },
  {
    name: "src",
    type: "string",
    access: "R/W",
    useCase: "Development/preview with JIT transcoding",
    category: "Media Source",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "src",
  },
  {
    name: "trimStart",
    type: "timestring",
    access: "R/W",
    useCase: "Relative trimming from start",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "trimstart",
  },
  {
    name: "trimEnd",
    type: "timestring",
    access: "R/W",
    useCase: "Relative trimming from end",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "trimend",
  },
  {
    name: "sourceIn",
    type: "timestring",
    access: "R/W",
    useCase: "Absolute source start time",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "sourcein",
  },
  {
    name: "sourceOut",
    type: "timestring",
    access: "R/W",
    useCase: "Absolute source end time",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "sourceout",
  },
  {
    name: "startTimeMs",
    type: "number",
    access: "R",
    useCase: "Element start in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "endTimeMs",
    type: "number",
    access: "R",
    useCase: "Element end in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "durationMs",
    type: "number",
    access: "R",
    useCase: "Element duration",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "currentTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "ownCurrentTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time in element scope",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "currentSourceTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time in source audio",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "parentTimegroup",
    type: "<ef-timegroup> | null",
    access: "R",
    useCase: "Immediate containing timegroup",
    category: "Hierarchy",
    domReadable: true,
  },
  {
    name: "rootTimegroup",
    type: "<ef-timegroup> | null",
    access: "R",
    useCase: "Root timeline timegroup",
    category: "Hierarchy",
    domReadable: true,
  },
  {
    name: "fftSize",
    type: "number",
    access: "R/W",
    useCase: "FFT frequency bins (power of 2)",
    category: "Audio Analysis",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "fft-size",
    defaultValue: "512",
  },
  {
    name: "fftDecay",
    type: "number",
    access: "R/W",
    useCase: "FFT smoothing frame count",
    category: "Audio Analysis",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "fft-decay",
    defaultValue: "8",
  },
  {
    name: "fftGain",
    type: "number",
    access: "R/W",
    useCase: "FFT amplitude multiplier",
    category: "Audio Analysis",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "fft-gain",
    defaultValue: "3",
  },
  {
    name: "interpolateFrequencies",
    type: "boolean",
    access: "R/W",
    useCase: "Interpolate missing frequencies",
    category: "Audio Analysis",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "interpolate-frequencies",
    defaultValue: "false",
  },
  {
    name: "mute",
    type: "boolean",
    access: "R/W",
    useCase: "Mute audio output",
    category: "Audio Analysis",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "mute",
    defaultValue: "false",
  },
];

