export interface PropertyDefinition {
  name: string;
  type: string;
  access: "R" | "W" | "R/W";
  useCase: string;
  category?: string;
  domReadable?: boolean | string;
  domWritable?: boolean | string;
  htmlAttribute?: boolean | string;
  defaultValue?: string;
}

export const captionsElementProperties: PropertyDefinition[] = [
  {
    name: "target",
    type: "string",
    access: "R/W",
    useCase: "ID of video or audio element to synchronize with",
    category: "Synchronization",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "target",
  },
  {
    name: "captionsSrc",
    type: "string",
    access: "R/W",
    useCase: "URL or path to external JSON file containing captions data",
    category: "Data Source",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "captions-src",
  },
  {
    name: "captionsData",
    type: "Caption | null",
    access: "R/W",
    useCase: "Direct captions data object (takes priority over captions-src and captions-script)",
    category: "Data Source",
    domReadable: true,
    domWritable: true,
  },
  {
    name: "captionsScript",
    type: "string",
    access: "R/W",
    useCase: "ID of script element containing JSON captions data",
    category: "Data Source",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "captions-script",
  },
  {
    name: "wordStyle",
    type: "string",
    access: "R/W",
    useCase: "CSS styling for active word elements",
    category: "Styling",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "word-style",
  },
  {
    name: "src",
    type: "string",
    access: "R/W",
    useCase: "Source path for caption file (inherited from EFSourceMixin)",
    category: "Data Source",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "src",
    defaultValue: '""',
  },
  {
    name: "durationMs",
    type: "number",
    access: "R",
    useCase: "Duration calculated from captions data (maximum end time)",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "startTimeMs",
    type: "number",
    access: "R",
    useCase: "Element start time in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "endTimeMs",
    type: "number",
    access: "R",
    useCase: "Element end time in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "currentTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "ownCurrentTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time in element scope",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "currentSourceTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time in source captions timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "trimStart",
    type: "timestring",
    access: "R/W",
    useCase: "Relative trimming from start",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "trimstart",
  },
  {
    name: "trimEnd",
    type: "timestring",
    access: "R/W",
    useCase: "Relative trimming from end",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "trimend",
  },
  {
    name: "sourceIn",
    type: "timestring",
    access: "R/W",
    useCase: "Absolute source start time",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "sourcein",
  },
  {
    name: "sourceOut",
    type: "timestring",
    access: "R/W",
    useCase: "Absolute source end time",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "sourceout",
  },
  {
    name: "offset",
    type: "timestring",
    access: "R/W",
    useCase: "Offset within parent timegroup",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "offset",
  },
  {
    name: "startOffsetMs",
    type: "number",
    access: "R",
    useCase: "Start offset in milliseconds (read-only)",
    category: "Time Coordinates",
    domReadable: true,
    htmlAttribute: "startoffset",
    defaultValue: "0",
  },
  {
    name: "duration",
    type: "timestring",
    access: "R/W",
    useCase: "Explicit duration override",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "duration",
  },
  {
    name: "parentTimegroup",
    type: "<ef-timegroup> | null",
    access: "R",
    useCase: "Immediate containing timegroup",
    category: "Hierarchy",
    domReadable: true,
  },
  {
    name: "rootTimegroup",
    type: "<ef-timegroup> | null",
    access: "R",
    useCase: "Root timeline timegroup",
    category: "Hierarchy",
    domReadable: true,
  },
  {
    name: "playing",
    type: "boolean",
    access: "R",
    useCase: "Whether playback is active",
    category: "Playback Control",
    domReadable: true,
  },
  {
    name: "loop",
    type: "boolean",
    access: "R/W",
    useCase: "Whether to loop playback",
    category: "Playback Control",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "loop",
  },
];


