import type { PropertyDefinition } from "./PropertyReference";

export const imageElementProperties: PropertyDefinition[] = [
  // Media Source
  {
    name: "assetId",
    type: "string",
    access: "R/W",
    useCase: "Production rendering with uploaded assets",
    category: "Media Source",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "asset-id",
  },
  {
    name: "src",
    type: "string",
    access: "R/W",
    useCase: "Development/preview with direct URLs or local files",
    category: "Media Source",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "src",
    defaultValue: '""',
  },
  // Temporal Composition
  {
    name: "duration",
    type: "timestring",
    access: "R/W",
    useCase: "Fixed duration for image (defaults to expanding to fill parent)",
    category: "Temporal Composition",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "duration",
  },
  {
    name: "offset",
    type: "timestring",
    access: "R/W",
    useCase: "Offset from natural start position in parent timegroup",
    category: "Temporal Composition",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "offset",
    defaultValue: "0",
  },
  {
    name: "loop",
    type: "boolean",
    access: "R/W",
    useCase: "Enable looping playback (only applies to root elements)",
    category: "Temporal Composition",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "loop",
    defaultValue: "false",
  },
  // Trimming
  {
    name: "trimStartMs",
    type: "number",
    access: "R/W",
    useCase: "Trim amount from start in milliseconds",
    category: "Trimming",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "trimstart",
  },
  {
    name: "trimEndMs",
    type: "number",
    access: "R/W",
    useCase: "Trim amount from end in milliseconds",
    category: "Trimming",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "trimend",
  },
  {
    name: "sourceInMs",
    type: "number",
    access: "R/W",
    useCase: "Source in-point in milliseconds (alternative to trimStart)",
    category: "Trimming",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "sourcein",
  },
  {
    name: "sourceOutMs",
    type: "number",
    access: "R/W",
    useCase: "Source out-point in milliseconds (alternative to trimEnd)",
    category: "Trimming",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "sourceout",
  },
  // Time Coordinates
  {
    name: "startTimeMs",
    type: "number",
    access: "R",
    useCase: "Element start in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "endTimeMs",
    type: "number",
    access: "R",
    useCase: "Element end in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "durationMs",
    type: "number",
    access: "R",
    useCase: "Computed element duration in milliseconds",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "currentTimeMs",
    type: "number",
    access: "R/W",
    useCase: "Current time in root timeline (writable on root elements)",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
  },
  {
    name: "ownCurrentTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time relative to element's own start",
    category: "Time Coordinates",
    domReadable: true,
  },
  // Playback
  {
    name: "playing",
    type: "boolean",
    access: "R",
    useCase: "Whether element is currently playing (root elements only)",
    category: "Playback",
    domReadable: true,
  },
  // Hierarchy
  {
    name: "parentTimegroup",
    type: "<ef-timegroup> | null",
    access: "R",
    useCase: "Immediate containing timegroup",
    category: "Hierarchy",
    domReadable: true,
  },
  {
    name: "rootTimegroup",
    type: "<ef-timegroup> | null",
    access: "R",
    useCase: "Root timeline timegroup",
    category: "Hierarchy",
    domReadable: true,
  },
];


