import type { PropertyDefinition } from "./PropertyReference";

export const imageElementProperties: PropertyDefinition[] = [
  {
    name: "assetId",
    type: "string",
    access: "R/W",
    useCase: "Production rendering with uploaded assets",
    category: "Media Source",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "asset-id",
  },
  {
    name: "src",
    type: "string",
    access: "R/W",
    useCase: "Development/preview with direct URLs or local files",
    category: "Media Source",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "src",
  },
  {
    name: "duration",
    type: "timestring",
    access: "R/W",
    useCase: "Fixed duration for image (defaults to expanding to fill parent)",
    category: "Temporal Composition",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "duration",
    defaultValue: "",
  },
  {
    name: "startTimeMs",
    type: "number",
    access: "R",
    useCase: "Element start in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "endTimeMs",
    type: "number",
    access: "R",
    useCase: "Element end in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "durationMs",
    type: "number",
    access: "R",
    useCase: "Element duration",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "currentTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "ownCurrentTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time in element scope",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "parentTimegroup",
    type: "<ef-timegroup> | null",
    access: "R",
    useCase: "Immediate containing timegroup",
    category: "Hierarchy",
    domReadable: true,
  },
  {
    name: "rootTimegroup",
    type: "<ef-timegroup> | null",
    access: "R",
    useCase: "Root timeline timegroup",
    category: "Hierarchy",
    domReadable: true,
  },
];


