import type { PropertyDefinition } from "./video-properties";

export const textElementProperties: PropertyDefinition[] = [
  // Text-specific properties
  {
    name: "split",
    type: "string",
    access: "R/W",
    useCase: "How to split text: 'line', 'word', or 'char'",
    category: "Text Splitting",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "split",
    defaultValue: "word",
  },
  {
    name: "stagger",
    type: "timestring",
    access: "R/W",
    useCase: "Stagger delay for sequential segment animations",
    category: "Animation Timing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "stagger",
  },
  {
    name: "easing",
    type: "string",
    access: "R/W",
    useCase: "Easing function for stagger distribution",
    category: "Animation Timing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "easing",
    defaultValue: "linear",
  },
  {
    name: "textContent",
    type: "string",
    access: "R/W",
    useCase: "Get or set the text content",
    category: "Content Management",
    domReadable: true,
    domWritable: true,
  },
  {
    name: "segments",
    type: "EFTextSegment[]",
    access: "R",
    useCase: "Get all created text segment elements",
    category: "Segment Access",
    domReadable: true,
  },
  {
    name: "whenSegmentsReady",
    type: "Promise<EFTextSegment[]>",
    access: "R",
    useCase: "Wait for segments to be created and initialized",
    category: "Segment Access",
    domReadable: true,
  },
  // Temporal properties (inherited from EFTemporal mixin)
  {
    name: "loop",
    type: "boolean",
    access: "R/W",
    useCase: "Enable looping playback",
    category: "Playback Control",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "loop",
    defaultValue: "false",
  },
  {
    name: "offset",
    type: "timestring",
    access: "R/W",
    useCase: "Offset from parent timegroup start position",
    category: "Temporal Positioning",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "offset",
    defaultValue: "0ms",
  },
  {
    name: "duration",
    type: "timestring",
    access: "R/W",
    useCase: "Explicit duration (overrides intrinsic duration)",
    category: "Temporal Positioning",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "duration",
  },
  {
    name: "durationMs",
    type: "number",
    access: "R",
    useCase: "Duration in milliseconds (calculated from content if not explicit)",
    category: "Temporal Positioning",
    domReadable: true,
  },
  {
    name: "trimstart",
    type: "timestring",
    access: "R/W",
    useCase: "Trim time from the start of the element",
    category: "Trimming",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "trimstart",
  },
  {
    name: "trimend",
    type: "timestring",
    access: "R/W",
    useCase: "Trim time from the end of the element",
    category: "Trimming",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "trimend",
  },
  {
    name: "sourcein",
    type: "timestring",
    access: "R/W",
    useCase: "Source in point - where to start within the source",
    category: "Source Manipulation",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "sourcein",
  },
  {
    name: "sourceout",
    type: "timestring",
    access: "R/W",
    useCase: "Source out point - where to end within the source",
    category: "Source Manipulation",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "sourceout",
  },
  {
    name: "startoffset",
    type: "timestring",
    access: "R/W",
    useCase: "Start offset for timing calculations",
    category: "Temporal Positioning",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "startoffset",
    defaultValue: "0ms",
  },
];


