import type { PropertyDefinition } from "./video-properties";

export const thumbnailStripProperties: PropertyDefinition[] = [
  {
    name: "target",
    type: "string",
    access: "R/W",
    useCase: "CSS selector ID of the target element (ef-video or root ef-timegroup) to generate thumbnails from",
    category: "Targeting",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "target",
    defaultValue: '""',
  },
  {
    name: "targetElement",
    type: "Element | null",
    access: "R/W",
    useCase: "Direct reference to target element (alternative to target selector)",
    category: "Targeting",
    domReadable: true,
    domWritable: true,
    htmlAttribute: null,
    defaultValue: "null",
  },
  {
    name: "thumbnailHeight",
    type: "number",
    access: "R/W",
    useCase: "Height of individual thumbnails in pixels (width calculated from aspect ratio)",
    category: "Layout",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "thumbnail-height",
    defaultValue: "24",
  },
  {
    name: "thumbnailSpacingPx",
    type: "number",
    access: "R/W",
    useCase: "Fixed visual spacing between thumbnails in pixels (consistent at all zoom levels)",
    category: "Layout",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "thumbnail-spacing-px",
    defaultValue: "48",
  },
  {
    name: "pixelsPerMs",
    type: "number",
    access: "R/W",
    useCase: "Pixels per millisecond for timeline scaling (used when not provided by timeline context)",
    category: "Layout",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "pixels-per-ms",
    defaultValue: "0.04",
  },
];


