import type { PropertyDefinition } from "./PropertyReference";

export const timegroupProperties: PropertyDefinition[] = [
  {
    name: "mode",
    type: "string",
    access: "R/W",
    useCase: "Temporal composition mode (fixed, sequence, contain, fit)",
    category: "Temporal Composition",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "mode",
    defaultValue: "contain",
  },
  {
    name: "overlap",
    type: "timestring",
    access: "R/W",
    useCase: "Overlap duration between sequential items in sequence mode",
    category: "Temporal Composition",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "overlap",
    defaultValue: "0s",
  },
  {
    name: "duration",
    type: "timestring",
    access: "R/W",
    useCase: "Explicit duration (only applies in fixed mode)",
    category: "Temporal Composition",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "duration",
    defaultValue: "",
  },
  {
    name: "currentTime",
    type: "number",
    access: "R/W",
    useCase: "Playback position in root timeline (seconds)",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "currenttime",
    defaultValue: "0",
  },
  {
    name: "currentTimeMs",
    type: "number",
    access: "R/W",
    useCase: "Playback position in root timeline (milliseconds)",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "currenttime",
    defaultValue: "0",
  },
  {
    name: "ownCurrentTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time in element's local timeline (milliseconds)",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "fit",
    type: "string",
    access: "R/W",
    useCase: "Visual scaling behavior (none, contain, cover)",
    category: "Visual Layout",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "fit",
    defaultValue: "none",
  },
  {
    name: "fps",
    type: "number",
    access: "R/W",
    useCase: "Frames per second for frame quantization",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "fps",
    defaultValue: "30",
  },
  {
    name: "effectiveFps",
    type: "number",
    access: "R",
    useCase: "Actual FPS being used (render options FPS during rendering, otherwise fps property)",
    category: "Time Coordinates",
    domReadable: true,
  },
];


