export interface PropertyDefinition {
  name: string;
  type: string;
  access: "R" | "W" | "R/W";
  useCase: string;
  category?: string;
  domReadable?: boolean | string;
  domWritable?: boolean | string;
  htmlAttribute?: boolean | string;
  defaultValue?: string;
}

export const waveformProperties: PropertyDefinition[] = [
  // Connection
  {
    name: "target",
    type: "string",
    access: "R/W",
    useCase: "Connect to audio or video element for visualization",
    category: "Connection",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "target",
    defaultValue: '""',
  },
  // Visual Style
  {
    name: "mode",
    type: "string",
    access: "R/W",
    useCase: "Visualization style (bars, wave, line, etc.)",
    category: "Visual Style",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "mode",
    defaultValue: "bars",
  },
  {
    name: "color",
    type: "string",
    access: "R/W",
    useCase: "Waveform color (CSS color value)",
    category: "Visual Style",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "color",
    defaultValue: "currentColor",
  },
  {
    name: "barSpacing",
    type: "number",
    access: "R/W",
    useCase: "Spacing between bars in bars/roundBars modes",
    category: "Visual Style",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "bar-spacing",
    defaultValue: "0.5",
  },
  {
    name: "lineWidth",
    type: "number",
    access: "R/W",
    useCase: "Line width for line and curve modes",
    category: "Visual Style",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "line-width",
    defaultValue: "4",
  },
  // Trimming & Editing
  {
    name: "trimStartMs",
    type: "timestring",
    access: "R/W",
    useCase: "Relative trimming from start",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "trimstart",
  },
  {
    name: "trimEndMs",
    type: "timestring",
    access: "R/W",
    useCase: "Relative trimming from end",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "trimend",
  },
  {
    name: "sourceInMs",
    type: "timestring",
    access: "R/W",
    useCase: "Absolute source start time",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "sourcein",
  },
  {
    name: "sourceOutMs",
    type: "timestring",
    access: "R/W",
    useCase: "Absolute source end time",
    category: "Trimming & Editing",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "sourceout",
  },
  // Time Coordinates
  {
    name: "startTimeMs",
    type: "number",
    access: "R",
    useCase: "Element start in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "endTimeMs",
    type: "number",
    access: "R",
    useCase: "Element end in root timeline",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "durationMs",
    type: "number",
    access: "R",
    useCase: "Computed element duration",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "duration",
    type: "timestring",
    access: "R/W",
    useCase: "Explicit duration override",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "duration",
  },
  {
    name: "offset",
    type: "timestring",
    access: "R/W",
    useCase: "Offset from parent start time",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "offset",
    defaultValue: "0",
  },
  {
    name: "startOffsetMs",
    type: "number",
    access: "R/W",
    useCase: "Start offset in milliseconds",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "startoffset",
    defaultValue: "0",
  },
  {
    name: "currentTimeMs",
    type: "number",
    access: "R/W",
    useCase: "Current time in root timeline",
    category: "Time Coordinates",
    domReadable: true,
    domWritable: true,
  },
  {
    name: "ownCurrentTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time in element scope",
    category: "Time Coordinates",
    domReadable: true,
  },
  {
    name: "currentSourceTimeMs",
    type: "number",
    access: "R",
    useCase: "Current time in source media",
    category: "Time Coordinates",
    domReadable: true,
  },
  // Playback
  {
    name: "loop",
    type: "boolean",
    access: "R/W",
    useCase: "Loop playback when reaching end",
    category: "Playback",
    domReadable: true,
    domWritable: true,
    htmlAttribute: "loop",
    defaultValue: "false",
  },
  // Hierarchy
  {
    name: "parentTimegroup",
    type: "<ef-timegroup> | null",
    access: "R",
    useCase: "Immediate containing timegroup",
    category: "Hierarchy",
    domReadable: true,
  },
  {
    name: "rootTimegroup",
    type: "<ef-timegroup> | null",
    access: "R",
    useCase: "Root timeline timegroup",
    category: "Hierarchy",
    domReadable: true,
  },
];


