FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY services/scheduler-go/go.mod services/scheduler-go/go.sum ./
COPY services/scheduler-go/ ./
COPY lib/queues/lua ./internal/redis/lua

RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /scheduler ./cmd/scheduler

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /scheduler .

EXPOSE 3000

CMD ["./scheduler"]

