services:
  graphql-engine:
    image: hasura/graphql-engine:v2.36.0
    volumes:
      - ${PWD}/services/graphql-engine/metadata:/hasura-metadata
      - ${PWD}/services/graphql-engine/migrations:/hasura-migrations
    ports:
      - "8080:8080"
    env_file:
      - ${PWD}/.env
    depends_on:
      data-connector-agent:
        condition: service_healthy
  # test-graphql-engine:
  #   image: hasura/graphql-engine:v2.36.0.cli-migrations-v3
  #   volumes:
  #     - ${PWD}/services/graphql-engine/metadata:/hasura-metadata
  #     - ${PWD}/services/graphql-engine/migrations:/hasura-migrations
  #   ports:
  #     - "9090:8080"
  #   env_file:
  #     - ${PWD}/.test-env
  #   depends_on:
  #     data-connector-agent:
  #       condition: service_healthy
  data-connector-agent:
    image: hasura/graphql-data-connector:v2.36.0
    ports:
      - 8081:8081
    environment:
      QUARKUS_LOG_LEVEL: ERROR # FATAL, ERROR, WARN, INFO, DEBUG, TRACE
      ## https://quarkus.io/guides/opentelemetry#configuration-reference
      QUARKUS_OPENTELEMETRY_ENABLED: "false"
      ## QUARKUS_OPENTELEMETRY_TRACER_EXPORTER_OTLP_ENDPOINT: http://tracing:4317
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/v1/athena/health"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
