ARG HASURA_VERSION=latest

FROM hasura/graphql-engine:${HASURA_VERSION}
RUN curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | VERSION=${HASURA_VERSION} bash

COPY ./metadata /metadata
COPY ./migrations /migrations
COPY ./config.prod.yaml /config.yaml
COPY ./migration-job.sh /migration-job.sh

CMD ["/bin/sh", "/migration-job.sh"]