#! /usr/bin/env bash
set -e

SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

"${SCRIPT_DIR}"/npm run typedoc \
  --workspace @editframe/api \
  --workspace @editframe/react \
  --workspace @editframe/elements \
  --workspace @editframe/assets
