/**
 * Script to generate asset mode test clips for browser testing
 * Creates track fragment indexes and track files that can be served by MSW during tests
 */

import { spawn } from "node:child_process";
import fsSync from "node:fs";
import fs from "node:fs/promises";
import path from "node:path";
import { generateTrackFromPath } from "../packages/assets/src/tasks/generateTrack.js";
import { generateTrackFragmentIndexFromPath } from "../packages/assets/src/tasks/generateTrackFragmentIndex.js";

const OUTPUT_DIR = path.join(process.cwd(), "test-assets", "asset-mode");
const SOURCE_VIDEO_DIR = path.join(process.cwd(), "../../lib/transcode/test-assets/transcode");

/**
 * Generate a test source video if it doesn't exist
 */
async function generateSourceVideo(): Promise<string> {
  const sourceVideoPath = path.join(SOURCE_VIDEO_DIR, "test-source-10s.mp4");

  try {
    await fs.access(sourceVideoPath);
    console.log(`✅ Using existing source video: ${sourceVideoPath}`);
    return sourceVideoPath;
  } catch {
    console.log(`📹 Generating test source video: ${sourceVideoPath}`);

    // Create source directory
    await fs.mkdir(SOURCE_VIDEO_DIR, { recursive: true });

    // Generate 10-second test video with frame numbers
    const ffmpegArgs = [
      "-y", // Overwrite
      "-f",
      "lavfi",
      "-i",
      "testsrc2=size=1920x1080:rate=25", // HD test pattern
      "-f",
      "lavfi",
      "-i",
      "sine=frequency=440:sample_rate=48000", // Audio
      "-t",
      "10", // 10 seconds
      "-vf",
      "drawtext=text='Frame\\: %{frame_num}\\nTime\\: %{pts\\:hms}':fontsize=48:fontcolor=white:box=1:boxcolor=black@0.8:x=(w-text_w)/2:y=(h-text_h)/2",
      "-c:v",
      "libx264",
      "-preset",
      "medium",
      "-crf",
      "23",
      "-g",
      "25", // GOP size
      "-c:a",
      "aac",
      "-b:a",
      "128k",
      "-movflags",
      "+faststart", // Head-moov for better streaming
      sourceVideoPath,
    ];

    await new Promise<void>((resolve, reject) => {
      const ffmpeg = spawn("ffmpeg", ffmpegArgs);

      ffmpeg.on("close", (code) => {
        if (code === 0) {
          console.log(`✅ Generated source video: ${sourceVideoPath}`);
          resolve();
        } else {
          reject(new Error(`FFmpeg failed with code ${code}`));
        }
      });

      ffmpeg.on("error", reject);
    });

    return sourceVideoPath;
  }
}

/**
 * Generate track fragment index and track files for a video
 */
async function generateAssetFiles(sourceVideoPath: string): Promise<void> {
  console.log(`🎬 Generating asset files for: ${sourceVideoPath}`);

  // Create output directory
  await fs.mkdir(OUTPUT_DIR, { recursive: true });

  // Generate track fragment index
  const fragmentIndex = await generateTrackFragmentIndexFromPath(sourceVideoPath);
  const indexPath = path.join(OUTPUT_DIR, "index.json");
  await fs.writeFile(indexPath, JSON.stringify(fragmentIndex, null, 2));
  console.log(`✅ Generated track fragment index: ${indexPath}`);

  // Generate track files for each track
  for (const [trackId, track] of Object.entries(fragmentIndex)) {
    console.log(`📼 Generating track ${trackId} (${track.type})`);
    const trackStream = await generateTrackFromPath(sourceVideoPath, Number(trackId));
    const trackPath = path.join(OUTPUT_DIR, `track-${trackId}.mp4`);
    const writeStream = fsSync.createWriteStream(trackPath);

    await new Promise<void>((resolve, reject) => {
      trackStream.pipe(writeStream);
      writeStream.on("finish", () => resolve());
      writeStream.on("error", reject);
    });

    console.log(`✅ Generated track file: ${trackPath}`);
  }
}

/**
 * Generate TypeScript constants for tests
 */
async function generateTestConstants(): Promise<void> {
  const indexData = await fs.readFile(path.join(OUTPUT_DIR, "index.json"), "utf-8");
  const fragmentIndex = JSON.parse(indexData);

  const tsContent = `/**
 * Generated asset mode test constants
 * Auto-generated by scripts/generate-asset-test-clips.ts
 */

export const ASSET_TEST_CLIPS = {
  sourceVideo: 'test-source-10s.mp4',
  baseUrl: 'file://${OUTPUT_DIR}',
  fragmentIndex: ${JSON.stringify(fragmentIndex, null, 2)} as const
} as const;

export type AssetTrackId = keyof typeof ASSET_TEST_CLIPS.fragmentIndex;
`;

  const tsPath = path.join(OUTPUT_DIR, "../asset-test-constants.ts");
  await fs.writeFile(tsPath, tsContent);

  console.log(`📝 Generated TypeScript constants: ${tsPath}`);
}

/**
 * Main function
 */
async function main(): Promise<void> {
  console.log("🎬 Asset Mode Test Clips Generator");
  console.log("=================================");

  try {
    // Generate or use existing source video
    const sourceVideoPath = await generateSourceVideo();

    // Generate asset files
    await generateAssetFiles(sourceVideoPath);

    // Generate constants
    await generateTestConstants();

    console.log("\n✅ All asset mode test clips generated successfully!");
  } catch (error) {
    console.error("💥 Fatal error:", error);
    process.exit(1);
  }
}

// Run if executed directly
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    console.error("💥 Fatal error:", error);
    process.exit(1);
  });
}

export { generateAssetFiles, OUTPUT_DIR };
