#!/bin/bash

set -ex

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

"${SCRIPT_DIR}"/docker-compose build ci-runner
"${SCRIPT_DIR}"/docker-compose run --rm ci-runner npm ci
"${SCRIPT_DIR}"/build-all
"${SCRIPT_DIR}"/docker-compose run --rm ci-runner npm run typedoc \
  --workspace @editframe/api \
  --workspace @editframe/react \
  --workspace @editframe/elements \
  --workspace @editframe/assets
"${SCRIPT_DIR}"/docker-compose run --rm ci-runner npm run typecheck --workspaces
"${SCRIPT_DIR}"/docker-compose run --rm ci-runner npm run lint
"${SCRIPT_DIR}"/docker-compose run --rm ci-runner npm run format
"${SCRIPT_DIR}"/docker-compose run --rm ci-runner npx vitest --config vitest.config.ts --run
"${SCRIPT_DIR}"/docker-compose run --rm ci-runner npx vitest --config vitest.config.browser.ts --run
