FROM node:22 AS installer

ENV NODE_ENV=production
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY package.json package-lock.json ./
ENV ELECTRON_SKIP_BINARY_DOWNLOAD=1
RUN npm install

COPY lib/ lib/
COPY services/scheduler/ services/scheduler/
COPY tsconfig.json ./

WORKDIR /app/services/scheduler
RUN npx vite build
RUN cp -r dist/* ./

WORKDIR /app
CMD ["/app/services/scheduler/server.js"]
