services:
  traefik:
    image: traefik:latest
    ports:
      - "7777:7777"
      - "3000:3000"
      - "24678:24678"
      - "3001:3001"
      - "4321:4321"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-shared
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=telecine-traefik
      - --entrypoints.web.address=:3000
      - --entrypoints.traefik.address=:7777
      - --entrypoints.port24678.address=:24678
      - --entrypoints.port3001.address=:3001
      - --entrypoints.elements.address=:4321
      - --log.level=INFO
      - --accesslog
      - --entrypoints.web.transport.respondingTimeouts.readTimeout=0s
      - --entrypoints.web.transport.respondingTimeouts.writeTimeout=0s
      - --entrypoints.web.transport.respondingTimeouts.idleTimeout=3600s
    restart: unless-stopped
    profiles:
      - main-worktree

  # autoheal:
  #   environment:
  #     AUTOHEAL_CONTAINER_LABEL: autoheal
  #   image: willfarrell/autoheal:latest
  #   network_mode: none
  #   restart: unless-stopped
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /var/run/docker.sock:/var/run/docker.sock

  runner:
    build:
      context: ./
      dockerfile: Dockerfile.runner
      tags:
        - telecine-runner
    env_file:
      - ${PWD}/.env
    restart: no
    environment:
      - PYTORCH_ENABLE_MPS_FALLBACK=1
    working_dir: /app
    volumes:
      - ${TELECINE_ROOT_HOST:-${PWD}}:/app
      - node_modules:/app/node_modules
      - ${HOME}/.config/gcloud:/root/.config/gcloud
      - ${ELEMENTS_PATH:-../elements}:/app/lib/packages
    devices:
      - /dev/mps0:/dev/mps0
    privileged: true
    stop_grace_period: 1s
    command: ["sleep", "infinity"]
    labels:
      - traefik.enable=false

  # playwright-runner:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.playwright.dev
  #     tags:
  #       - playwright-runner
  #   platform: linux/amd64
  #   pull_policy: never
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #     - node_modules_amd64:/app/node_modules
  #     - ${HOME}/.config/gcloud:/root/.config/gcloud
  #     - ../elements:/app/lib/packages
  #   stop_grace_period: 1s
  #   init: true
  #   command: ["sh", "-c", "npm install && sleep infinity"]

  # playwright-shell:
  #   image: playwright-runner
  #   depends_on:
  #     - playwright-runner
  #   working_dir: /app
  #   volumes_from:
  #     - playwright-runner
  #   command: "zsh"

volumes:
  node_modules:
  node_modules_amd64:

networks:
  traefik-shared:
    name: telecine-traefik
    external: true
  default:
    name: ${WORKTREE_DOCKER_NETWORK_NAME:-telecine_default}
