-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "video2"."renders" add column "restricted" boolean
--  not null default 'false';
