-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "video2"."process_html" add column "created_at" timestamptz
--  null default now();
