-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "video2"."isobmff_files" add column "index_uploaded" boolean
--  null default 'false';
