services:
  transcribe:
    image: telecine-runner
    pull_policy: never
    env_file:
      - ${PWD}/.env
    depends_on:
      - runner
    working_dir: /app
    environment:
      - SHELL=/bin/sh
      - OTEL_SERVICE_NAME=transcribe
      - PYTORCH_ENABLE_MPS_FALLBACK=1
    volumes_from:
      - runner
    stop_grace_period: 1s
    init: true
    command: [ "--loader", "/app/loader.js", "--watch", "/app/services/transcribe/src/server.ts" ]
    labels:
      traefik.http.routers.transcribe.rule: Host(`localhost`) && PathPrefix(`/_/transcribe`)
      traefik.http.routers.transcribe.entrypoints: web
      traefik.http.services.transcribe.loadbalancer.server.port: 3000
