name: 'Run Typecheck'
description: 'Run typecheck script'
runs:
  using: "composite"
  steps:
    # AUDIT: Not clear there's a benefit to running this as a separate step.
    - name: Run typecheck script
      run: ./integration/typecheck
      shell: bash
      working-directory: ${{ github.workspace }}