/**
 * Generated JIT test clip constants
 * Auto-generated by scripts/generate-jit-test-clips.ts
 */

export const JIT_TEST_CLIPS = {
  sourceVideo: "test-source-10s.mp4",
  baseUrl: "file:///app/lib/packages/test-assets/jit-segments",
  segments: {
    "segment-0ms-2s-low": {
      startTimeMs: 0,
      durationMs: 2000,
      quality: "low" as const,
      filename: "segment-0ms-2s-low.mp4",
      cacheKey: "test-source:0:low",
    },
    "segment-0ms-2s-medium": {
      startTimeMs: 0,
      durationMs: 2000,
      quality: "medium" as const,
      filename: "segment-0ms-2s-medium.mp4",
      cacheKey: "test-source:0:medium",
    },
    "segment-0ms-2s-high": {
      startTimeMs: 0,
      durationMs: 2000,
      quality: "high" as const,
      filename: "segment-0ms-2s-high.mp4",
      cacheKey: "test-source:0:high",
    },
    "segment-2000ms-2s-medium": {
      startTimeMs: 2000,
      durationMs: 2000,
      quality: "medium" as const,
      filename: "segment-2000ms-2s-medium.mp4",
      cacheKey: "test-source:2000:medium",
    },
    "segment-4000ms-2s-medium": {
      startTimeMs: 4000,
      durationMs: 2000,
      quality: "medium" as const,
      filename: "segment-4000ms-2s-medium.mp4",
      cacheKey: "test-source:4000:medium",
    },
    "segment-0ms-4s-medium": {
      startTimeMs: 0,
      durationMs: 4000,
      quality: "medium" as const,
      filename: "segment-0ms-4s-medium.mp4",
      cacheKey: "test-source:0:medium",
    },
    "segment-6000ms-1s-low": {
      startTimeMs: 6000,
      durationMs: 1000,
      quality: "low" as const,
      filename: "segment-6000ms-1s-low.mp4",
      cacheKey: "test-source:6000:low",
    },
  },
} as const;

export type JitTestClipKey = keyof typeof JIT_TEST_CLIPS.segments;
