name: 'Google Cloud Authentication'
description: 'Authenticate with Google Cloud'
runs:
  using: "composite"
  steps:
    # AUDIT: This action hard-codes the project and workload identity provider. These could be integrated with the deploy/ code to be controlled by single source of truth.
    - uses: google-github-actions/auth@v2
      with:
        project_id: "editframe"
        workload_identity_provider: "projects/257055402370/locations/global/workloadIdentityPools/telecine-deployer/providers/github"
    - name: Configure Docker for GCR
      shell: bash
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
