#!/usr/bin/env bash
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

xvfb-run -a \
  /electron-build/electron --no-sandbox \
  "$SCRIPT_DIR/exec-electron-test.js"
