#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

set -ex

docker build \
  ${SCRIPT_DIR}/.. \
  -f ${SCRIPT_DIR}/../Dockerfile.runner \
  --platform=linux/amd64 \
  -t telecine:deps \
  -t telecine:runner \
  -t telecine-runner
