#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

"${SCRIPT_DIR}"/npm version prerelease --preid beta --workspaces 
"${SCRIPT_DIR}"/npm version prerelease --preid beta
