#!/usr/bin/env bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
PROJECT_ROOT="$SCRIPT_DIR/.."

cd "$PROJECT_ROOT"

WAIT_FOR_ACTION=false
BRANCH="main"

while [[ $# -gt 0 ]]; do
  case $1 in
    --wait)
      WAIT_FOR_ACTION=true
      shift
      ;;
    --branch)
      BRANCH="$2"
      shift 2
      ;;
    *)
      BRANCH="$1"
      shift
      ;;
  esac
done

git subtree push --prefix=elements elements "$BRANCH" 2>&1

echo "pushed elements -> ${BRANCH}"

if [ "$WAIT_FOR_ACTION" = "true" ]; then
  "$SCRIPT_DIR/wait-for-elements-action" "release.yaml"
fi
