#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Detect if we have a TTY
if [ -t 0 ]; then
    TTY_FLAGS="-it"
else
    TTY_FLAGS=""
fi

$SCRIPT_DIR/docker-compose run $TTY_FLAGS --rm runner npx vitest "$@"
