-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE VIEW "identity"."valid_email_confirmations" AS
--  SELECT id,
--     created_at,
--     updated_at,
--     confirmed_at,
--     user_id,
--     confirmation_token
--    FROM identity.email_confirmations
--   WHERE ((confirmed_at IS NULL) AND (created_at >= (now() - '14 days'::interval)))
--   ORDER BY created_at DESC;
