services:
  jit-transcoding:
    profiles: ["render"]
    image: telecine-runner
    pull_policy: never
    env_file:
      - ${PWD}/.env
    depends_on:
      - runner
    working_dir: /app
    environment:
      - SHELL=/bin/sh
      - OTEL_SERVICE_NAME=jit-transcoding
      - PORT=3001
    volumes_from:
      - runner
    stop_grace_period: 1s
    init: true
    networks:
      - default
      - traefik-shared
    command: ["npx", "tsx", "--watch", "/app/services/jit-transcoding/server.ts" ]
    labels:
      traefik.enable: true
      traefik.http.routers.jit-transcoding-${WORKTREE_ID:-main}.rule: "Host(`${WORKTREE_DOMAIN:-localhost}`) && PathPrefix(`/api/v1/transcode`)"
      traefik.http.routers.jit-transcoding-${WORKTREE_ID:-main}.entrypoints: web
      traefik.http.routers.jit-transcoding-${WORKTREE_ID:-main}.priority: 1000
      traefik.http.routers.jit-transcoding-${WORKTREE_ID:-main}.service: jit-transcoding-${WORKTREE_ID:-main}
      traefik.http.services.jit-transcoding-${WORKTREE_ID:-main}.loadbalancer.server.port: 3001

networks:
  traefik-shared:
    name: editframe-shared
    external: true