-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION generate_webhook_secret()
-- RETURNS TEXT AS $$
-- BEGIN
--     RETURN 'ef_webhook_' || replace(uuid_generate_v4()::text, '-', '');
-- END;
-- $$ LANGUAGE plpgsql;
