-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "video2"."caption_files" add column "complete" boolean
--  null default 'false';
