-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "video2"."image_files" add column "next_byte" integer
--  not null default '0';
