name: 'Pull and Retag Runner Image'
description: 'Pull runner image from GCR and retag it for local use'
inputs:
  cache-key:
    description: 'Cache key used to tag the runner image'
    required: true
  image-name:
    description: 'Full name of the runner image in GCR'
    required: true
  local-tag:
    description: 'Tag to use for the local image'
    required: true
runs:
  using: "composite"
  steps:
    - name: Pull and retag Docker image
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        docker pull ${{ inputs.image-name }}:${{ inputs.cache-key }}
        docker tag ${{ inputs.image-name }}:${{ inputs.cache-key }} ${{ inputs.local-tag }} 