services:
  web:
    image: telecine-runner
    pull_policy: never
    env_file:
      - ${PWD}/.env
    environment:
      - OTEL_SERVICE_NAME="web"
      - VITE_HMR_HOST=${WORKTREE_DOMAIN:-localhost}
      - VITE_WEB_HOST=http://${WORKTREE_DOMAIN:-localhost}:3000
      - WEB_HOST=http://${WORKTREE_DOMAIN:-localhost}:3000
    working_dir: /app
    volumes_from:
      - runner
    #  Layering a volume over the render diretory hides the render directory. This fixes some unfortunate reload behaviors with vite.
    volumes:
      - /app/services/render
    stop_grace_period: 1s
    networks:
      - default
      - traefik-shared

    # prettier-ignore
    command: ["node", "/app/services/web/server.js"]
    depends_on:
      - runner
      - postgres
      - graphql-engine
    labels:
      traefik.enable: true

      traefik.http.routers.web-chore-gitignore-cleanup-32jwk.rule: "Host(`${WORKTREE_DOMAIN:-localhost}`) || Host(`host.docker.internal`)"
      traefik.http.routers.web-chore-gitignore-cleanup-32jwk.entrypoints: web
      traefik.http.routers.web-chore-gitignore-cleanup-32jwk.service: web-chore-gitignore-cleanup-32jwk
      traefik.http.routers.web-chore-gitignore-cleanup-32jwk.priority: 1
      traefik.http.services.web-chore-gitignore-cleanup-32jwk.loadbalancer.server.port: 3000

      traefik.http.routers.web24678-chore-gitignore-cleanup-32jwk.rule: Host(`${WORKTREE_DOMAIN:-localhost}`)
      traefik.http.routers.web24678-chore-gitignore-cleanup-32jwk.entrypoints: port24678
      traefik.http.routers.web24678-chore-gitignore-cleanup-32jwk.service: web24678-chore-gitignore-cleanup-32jwk
      traefik.http.services.web24678-chore-gitignore-cleanup-32jwk.loadbalancer.server.port: 24678

      traefik.http.routers.web3001-chore-gitignore-cleanup-32jwk.rule: Host(`${WORKTREE_DOMAIN:-localhost}`)
      traefik.http.routers.web3001-chore-gitignore-cleanup-32jwk.entrypoints: port3001
      traefik.http.routers.web3001-chore-gitignore-cleanup-32jwk.service: web3001-chore-gitignore-cleanup-32jwk
      traefik.http.services.web3001-chore-gitignore-cleanup-32jwk.loadbalancer.server.port: 3001

networks:
  traefik-shared:
    name: telecine-traefik
    external: true
